//===----------------------------------------------------------------------===//
// KotlinSwift2JavaGenerator.swift
// Generates Kotlin JVM stubs from imported Swift declarations.
//===----------------------------------------------------------------------===//

import SwiftJavaConfigurationShared
import struct Foundation.URL
import Foundation

package class KotlinSwift2JavaGenerator: Swift2JavaGenerator {
  let config: Configuration
  let analysis: AnalysisResult
  let translator: Swift2JavaTranslator
  let swiftOutputDirectory: String
  let swiftModuleName: String
  let kotlinOutputDirectory: String

  package init(
    config: Configuration,
    translator: Swift2JavaTranslator,
    swiftOutputDirectory: String,
    kotlinOutputDirectory: String
  ) {
    self.config = config
    self.translator = translator
    self.analysis = translator.result
    self.swiftModuleName = translator.swiftModuleName
    self.swiftOutputDirectory = swiftOutputDirectory
    self.kotlinOutputDirectory = kotlinOutputDirectory
  }

  package func generate() throws {
    let jniGenerator = JNISwift2JavaGenerator(
        config: self.config,
        translator: translator,
        javaPackage: "",
        swiftOutputDirectory: swiftOutputDirectory,
        javaOutputDirectory: kotlinOutputDirectory,
        javaClassLookupTable: [:]
    )
    try jniGenerator.writeSwiftThunkSources()

    var printer = CodePrinter()
    printModule(&printer)

    let outputDir = URL(fileURLWithPath: kotlinOutputDirectory)
    try FileManager.default.createDirectory(at: outputDir, withIntermediateDirectories: true)

    let outputFile = outputDir.appendingPathComponent("\(swiftModuleName).kt")
    try printer.contents.write(to: outputFile, atomically: true, encoding: .utf8)

    print("Generated Kotlin: \(outputFile.path)")
}

  func printModule(_ printer: inout CodePrinter) {
    printer.print(
        """
        // Generated by swift-java
        // Swift module: \(swiftModuleName)

        """
    )

    printer.printBraceBlock("object \(swiftModuleName)") { printer in
        printer.print(
            """
            init {
                System.loadLibrary("swiftCore")
                System.loadLibrary("\(swiftModuleName)")
            }

            """
        )
        for decl in analysis.importedGlobalFuncs {
            printFunction(&printer, decl)
        }
    }
  }

  func printFunction(_ printer: inout CodePrinter, _ decl: ImportedFunc) {
    let params = decl.functionSignature.parameters
        .enumerated()
        .map { (i, param) in
            let name = param.parameterName ?? "_\(i)"
            let type = mapSwiftTypeToKotlin(param.type)
            return "\(name): \(type)"
        }
        .joined(separator: ", ")

    let paramNames = decl.functionSignature.parameters
        .enumerated()
        .map { (i, param) in param.parameterName ?? "_\(i)" }
        .joined(separator: ", ")

    let returnType = mapSwiftTypeToKotlin(decl.functionSignature.result.type)
    let returnClause = returnType == "Unit" ? "" : ": \(returnType)"

    printer.print("private external fun `$\(decl.name)`(\(params))\(returnClause)")
    printer.print("fun \(decl.name)(\(params))\(returnClause) = `$\(decl.name)`(\(paramNames))")
    printer.print("")
  }

  func mapSwiftTypeToKotlin(_ type: SwiftType) -> String {
    // Get the type name as a string and map it
    let typeName = "\(type)"

    switch typeName {
    case "Int", "Int64":     return "Long"
    case "Int32":            return "Int"
    case "Bool":             return "Boolean"
    case "Double":           return "Double"
    case "Float":            return "Float"
    case "String":           return "String"
    case "Void", "()":       return "Unit"
    default:                 return typeName
    }
  }
}
